# Generated by Django 4.2.2 on 2023-06-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formuario', '0002_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='nome_mãe',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
